### ISSUE TITLE
Can't scroll ScrollView in panel

### ISSUE THREAD

**Issue by arxdeus** [luciano-work/we_slide#10]
Hello, is there's any way to implement vertical scrolling in panel widget?
Horizontal scrolling via PageView works fine, so, i think, it will be good if vertical scrolling will works too

**Comment by lannodev** [comment]
Hi @MindMayhem  👋,
I will try to identify why this happens.

**Comment by arxdeus** [comment]
@luciano-work any news?

**Comment by lannodev** [comment]
Sorry @MindMayhem, I'm on vacation. I will be back next week

**Comment by arxdeus** [comment]
Ok, no problem, get well, friend!

вт, 28 дек. 2021 г., 14:39 Luciano Oliveira ***@***.***>:

**Comment by lannodev** [comment]
Hi @MindMayhem
I found a way to make the panel work with a listview, but panel header needs to be visible.
My example: https://dartpad.dev/?id=e82909f2018c2af9f5cc4740dc9fb568

The stack components inside WeSlide use Slide Transition class, I don't know how to make works with listview.
In Material Backdrop has a panel header too
https://material.io/components/backdrop#behavior
https://kstatic.googleusercontent.com/files/fc37a081b732898318bdab49191a602e735bb162b04b98fdc3bb4a92b1b7d07b0749d156f6308d365eaa2a0b5988cdfd34d446cf0099ab26665a8387d3a5e64d

Please, if you know how to do it, make a pull request and collaborate with this project :)

**Comment by khodemobin** [comment]
any change? i have the issue too

**Comment by lannodev** [comment]
Hi @khodemobin ,
Please, have you tried to follow my example?
https://dartpad.dev/?id=e82909f2018c2af9f5cc4740dc9fb568

**Comment by himanshusharmaek** [comment]
> https://dartpad.dev/?id=e82909f2018c2af9f5cc4740dc9fb568
Hi @luciano-work 
this example not working on android device

**Comment by himanshusharmaek** [comment]
any idea how I can achieve this in android @luciano-work

**Comment by lannodev** [comment]
Hi @himanshusharmaek,
I'll try to understand why it's not working on android devices, but that might take a while, at the moment I'm really busy with other things.
