### ISSUE TITLE
Using FAB with we slide

### ISSUE THREAD

**Issue by devqcf** [luciano-work/we_slide#11]
My app is a music player. I have scaffold and a FAB. The problem is that FAB is higher than it should be. 

Code:
```
return Scaffold(
      body: WeSlide(
          panelMaxSize:
              (WidgetsBinding.instance?.window.physicalSize.height ?? 0) / 2,
          panelMinSize: 180.0,
          backgroundColor: Colors.white24,
          panel: PlayerScreen(),
          panelHeader: Player(),
          body: Scaffold(
              appBar: AppBar(title: const Text("Player")),
              floatingActionButton: Container(
                margin: EdgeInsets.only(bottom: 50.0),
                child: FloatingActionButton(
                  onPressed: () {
                    _showAddDialog();
                  },
                  child: Icon(Icons.add),
                ),
              ),
              body: MusicList())
          // ),
          ),
    );
```

![Simulator Screen Shot - iPhone 12 - 2021-12-16 at 16 04 45](https://user-images.githubusercontent.com/70290804/146360679-cf0f5507-2e74-4881-b53f-422e7d8db971.png)

**Comment by lannodev** [comment]
Hi @deargosep 👋,
I will try to reproduce this issue as soon as possible.

**Comment by arxdeus** [comment]
@deargosep 
if you using any reactive state managment package, then u can try it:

1. Create `WeSlideController? weSlideController = WeSlideController();`
2. Attach it to your panel `controller: weSlideController`
3. Wrap your FAB to _[Your reactive handler]_ and then to `Visibility` widget
4. Attach `weSlideController.isOpened` to **Visibility** `visible` argument

My best choice - **GetX** package with `Obx(()=> _Widget_)` reactive handler

**Comment by lannodev** [comment]
Hi @deargosep,
I didn't find any problem to create FAB inside the body.
Please see my example
https://dartpad.dev/?id=5f57c8eb5aedabbd79847e522f447564
