### ISSUE TITLE
[Feature] Need to extends the body behind the appbar and the footer

### ISSUE THREAD

**Issue by yelkamel** [luciano-work/we_slide#12]
I have requirement to show the bottom tabbar and the footer with borderradius 

but when I don't have the body in the back of behind the footer / bottomtabbar.

**Comment by yelkamel** [comment]
I did the change, I create a new branch and I wanted to do a pull request but I was not able to push.

so I forked it here: https://github.com/yelkamel/we_slide

**Comment by lannodev** [comment]
Hi @yelkamel 👋
Have you tried to fork, edit, commit and submit a pull request? 
There is no restrictions to make pull request.
Please, could you send me an example using darpad, like this: 
https://dartpad.dev/?id=6a833cba62679260bf1a556a4fdc9043
