### ISSUE TITLE
WeSlider For my whole app

### ISSUE THREAD

**Issue by VocsySatyam** [luciano-work/we_slide#16]
How can I open my we slide and show in all the screens in my app?

**Comment by lannodev** [comment]
Hi @VocsySatyam 👋
you can put your pages inside the body using indexedStack:

```dart
body: IndexedStack(
  index: controller.indexPage,
  children: [
    Page1(),
    Page2(),
    Page3(),
    Page4(),
    Page5(),
   ],
 ),
```

**Comment by zhushenwudi** [comment]
> Hi @VocsySatyam 👋 you can put your pages inside the body using indexedStack:
> 
> ```dart
> body: IndexedStack(
>   index: controller.indexPage,
>   children: [
>     Page1(),
>     Page2(),
>     Page3(),
>     Page4(),
>     Page5(),
>    ],
>  ),
> ```

I have a question, how to use route navigation inside the body through GetX?
