### ISSUE TITLE
panel widget refresh

### ISSUE THREAD

**Issue by nice2cu1** [luciano-work/we_slide#19]
Can I notify the panel component to refresh when the panel is show()? I have a string that needs to be transformed according to a condition when the panel is displayed, I use getx to no work, please help me, thanks.

this is my code
https://paste.gg/p/anonymous/85237a62eb1d4afc9e16528bbaa5ad20/files/8b4a1b1e3d5d4d75822aca8a1d042f99/raw

**Comment by lannodev** [comment]
Hi @nice2cu1 👋
Before running your example, can you tell me if this issue #2  is the same as yours?

**Comment by nice2cu1** [comment]
> 嗨@nice2cu1 👋在运行您的示例之前，您能告诉我这个问题#2是否与您的问题相同吗？

Solved my problem, thanks!
