### ISSUE TITLE
Persistent navigation bar and panelHeader

### ISSUE THREAD

**Issue by suiebay** [luciano-work/we_slide#24]
Hi, thanks for the wonderful package!

My question is how to implement persistent navigation bar and panel header? For example, when I open other screens from the main navigation screens, the bottom navigation bar and the panel header should not disappear, they should remain. For example. in spotify when user opens album or other such screens from main screen the bottom navigation bar and panel remain and stay on album screen, how to implement this feature?

Thank you

**Comment by lannodev** [comment]
Hi @suiebay 
If you want to persist the weslide like navigation Bar or appBar, then you need to set your routes inside the body widget
```dart
body: IndexedStack(
  index: controller.indexPage,
  children: [
    RouterOutlet(module: ExploreModule()),
    //FavoriteModule(),
    // SearchModule(),
    //LibraryModule(),
    // LibraryModule(),
  ],
),
```
In the above example I am using the flutter_modular package
https://pub.dev/documentation/flutter_modular/latest/flutter_modular/RouterOutlet-class.html
There is a video about flutter_modular RouterOutlet but it is in portuguese: https://www.youtube.com/watch?v=69TRRRcazqk
I hope to answered your question ;)

**Comment by suiebay** [comment]
Thank you for your response

Till your response I searched for some features that can do it, and found that wrapping the screens of body with `CupertinoTabView` can do what i want :) I don't know how correct my way of implementation but I would take a look for your answer

I close the issue because the question has been answered 👍
