### ISSUE TITLE
The damping is too large when the slide is opened, I hope you can add a parameter to adjust the damping when the slide is opened or closed

### ISSUE THREAD

**Issue by 2697a** [luciano-work/we_slide#3]
The damping is too large when the slide is opened, I hope you can add a parameter to adjust the damping when the slide is opened or closed

**Comment by lannodev** [comment]
Hi @2697a,
When you say "damping is too large" are you referring to the duration of the animation?

**Comment by 2697a** [comment]
It's not easy to open and close



> Hi @2697a,
> When you say "damping is too large" are you referring to the duration of the animation?

It's not easy to open and close

![Video_20210312_073752_964](https://user-images.githubusercontent.com/24308269/110936004-2aef5780-836b-11eb-95b9-5c948f060b7e.gif)

**Comment by lannodev** [comment]
Thank you @2697a, I will try to fix this soon

**Comment by 2697a** [comment]
> Thank you @2697a, I will try to fix this soon

好的，辛苦了
