### ISSUE TITLE
Can the page be minimized by slide down gesture?

### ISSUE THREAD

**Issue by aytunch** [luciano-work/we_slide#5]
Thanks for the package,
Are we limited by a single press action?
It would also be cool to add an optional fade out and size down properties for the front page. Just like an Instagram story view being dismissed along with our finger gestures.

**Comment by lannodev** [comment]
Hi @aytunch 👋
Please, could you give me an example?

**Comment by lannodev** [comment]
For lack of more information this issue is being closed
